[package]
name = "pibot"
version = "0.1.0"
edition = "2024"

[dependencies]
atrium-api = "0.25.0"
bsky-sdk = "0.1.16"
fastrand = "2.3.0"
reqwest = "0.12.12"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.140"
tokio = {version = "1.44.0", features = ["full"]}
